apiVersion: apps/v1
kind: Deployment
metadata:
  name: racer-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racer-login
  template:
    metadata:
      labels:
        app: racer-login
    spec:
      containers:
      - name: racer-login
        image: <your-dockerhub-username>/racer-login:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: racer-db
          mountPath: /app/racer.db
          subPath: racer.db
      volumes:
      - name: racer-db
        emptyDir: {}
